controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
api_generate_text:
  path: /generate-text
  controller: App\Controller\OpenAiController::generateText
  methods: [POST]
